### ISSUE TITLE
Consulta sobre get_microdata

### ISSUE THREAD

**Issue by andresfortunato** [DiegoKoz/Curso_R_EPH_clases#1]
Hola! Antes que nada, gracias por desarrollar esta herramienta! Es sencillamente espectacular. No sé si este es el lugar para hacer una consulta, pero me parecía más apropiado que en el git de la eph directo. El problema que tengo es que las encuestas que quiero bajar ya no están disponibles. Pude acceder a bases desde 2007 a 2019, pero de repente get_microdata solo me consigue de 2011 a 2014. ¿Alguien sabe que puede estar pasando? ¿Hay algo que pueda hacer para solucionarlo? Muchisimas gracias!

**Comment by pablotis** [comment]
Buenas!
Muchas gracias por tus palabras, nos alegra mucho que sirva!
Sobre el lugar para la consulta, el más cómodo es este: https://github.com/holatam/eph/issues

Sobre el error en particular, tendrás la salida de lo que devuelve R al no poder bajarlas? Es con algún trimestre en particular?
Acabo de probar esto:

```
 base_serie_ind <- get_microdata(year = 2007:2019, trimester = 1, type = "individual")
 
 base_serie_ind_2 <- base_serie_ind %>% 
   select(microdata) %>% 
   unnest(microdata)
```

y me funcionó bien:
![imagen](https://user-images.githubusercontent.com/30708601/100617616-85533380-32f9-11eb-8881-4a76fae4721e.png)

**Comment by andresfortunato** [comment]
Mil gracias Pablo! La sigo en el [issues de eph](https://github.com/holatam/eph/issues/26#issue-753668447) entonces así queda ahí!
